### PR TITLE
replace instanceof Array and instanceof Buffer with Array.isArray and Buffer.isBuffer

### PR DESCRIPTION
**Pull request by Uzlopak**
replace instanceof Array and instanceof Buffer with Array.isArray and Buffer.isBuffer

I dont know which one we prefer in fastify. Would be imho good if we had some styleguide

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by RafaelGSS — COMMENTED** [review]
Any reason to update it? Is it performance or just a style guide?

**Comment by Uzlopak** [comment]
Style

**Review by mcollina — CHANGES_REQUESTED** [review]
I would _never_ use Buffer.isBuffer(). It's a relic of the past.

instanceof works great for this given they are "native" types too

**Comment by Uzlopak** [comment]
what about Array.isArray?

**Comment by mcollina** [comment]
I don't see the point in changing this for no specific value. I don't see how one is more readable than others, and I don't want to establish any pattern or rule across the org.

**Comment by Uzlopak** [comment]
fair enough

**Pull request closed without merging**
