### PR TITLE
Improve coverage

### LINKED ISSUE #67: Coverage 100%
Improve Coverage to meet 100%

### PR DESCRIPTION
**Pull request by MSE99**
Fixes #67 

This PR adds additional tests that boost the overall test coverage to 100%, it also fixes an [unrecorded bug](https://github.com/fastify/fastify-secure-session/blob/master/index.js#L49) at line 49 which caused buffer keys that are passed inside an array to the `key` option prop not be validated because of implicit coercion the `<` operator will always return `false`.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
Can you attach coverage report? If the coverage reach 100% in all fields can you remove this line https://github.com/fastify/fastify-secure-session/blob/master/.taprc#L1

**Comment by MSE99** [comment]
Here's the test coverage

Screenshot from 2021-04-30 11-48-14

**Comment by climba03003** [comment]
Can you remove this line https://github.com/fastify/fastify-secure-session/blob/master/.taprc#L1? Since it reached 100%, we should check the coverage and ensure it will not drop again.

Thanks for your works.

**Comment by zekth** [comment]
Looks good on my machine but the ci tends to be flaky on `nonce-bad-length.test.js`. Is is due to the fact we don't use the `tap.test` directive in this file?

**Comment by MSE99** [comment]
@zekth the tests occasionally sigfault when you run them using tap via  `npm test` or `npx <test-filename>.js` executing `nonce-bad-length.test.js` directly with node works fine, both `cookie-name.js` and `path.js` have the same issue.

**Comment by zekth** [comment]
Do you have an idea what causes this? To me we can land this PR but we definitely need to address this issue.

**Comment by mcollina** [comment]
Let's see if we can get a passing CI run.

**Comment by MSE99** [comment]
@zekth I think it's a problem with node 12, it sometimes prints the following error when running `path.js` using `npm test`:

```
test/path.js 2> FATAL ERROR: HandleScope::HandleScope Entering the V8 API without proper locking in place
test/path.js 2>  1: 0xa1a640 node::Abort() [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2>  2: 0xa1aa4c node::OnFatalError(char const*, char const*) [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2>  3: 0xb9a45a v8::Utils::ReportApiFailure(char const*, char const*) [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2>  4: 0xb9b9fe v8::HandleScope::HandleScope(v8::Isolate*) [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2>  5: 0x9f07f5 node::CallbackQueue<void, node::Environment*>::CallbackImpl<node_napi_env__::CallFinalizer(void (*)(napi_env__*, void*, void*), void*, void*)::{lambda(node::Environment*)#1}>::Call(node::Environment*) [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2>  6: 0x9bbdb6 node::Environment::RunAndClearNativeImmediates(bool) [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2>  7: 0x9c912d node::Environment::CleanupHandles() [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2>  8: 0x9c9552 node::Environment::RunCleanup() [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2>  9: 0x988d67 node::FreeEnvironment(node::Environment*) [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2> 10: 0xa5d6bf node::NodeMainInstance::Run() [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2> 11: 0x9eab6c node::Start(int, char**) [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
test/path.js 2> 12: 0x7f82ce546cb2 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
test/path.js 2> 13: 0x981fe5  [/home/mohamededrah/.nvm/versions/node/v12.22.1/bin/node]
```

but it also could be tap (or one of it's dependencies).

**Comment by mcollina** [comment]
This looks like a problem in sodium-native (likely) or node itself (unlikely).

**Comment by zekth** [comment]
Tried of 12.18 and 12.22 and so far after 20 iterations on MAC os i cannot reproduce.

**Comment by MSE99** [comment]
I was only able to reproduce on node versions 12.19 and up, node version 12.18 works fine, on 12.22 `path.js`, `malformed-cookie.js`, `nonce-bad-length.js` have a high failure chance

**Comment by mcollina** [comment]
Can you isolate it to a single test?

**Comment by MSE99** [comment]
I couldn't solve the problem, but i noticed a few interesting things:

1. 1 to 3 (sometimes up to 5 tests will fail although this only happened once)  test suits/files will always fail no matter what (even if you keep one test file and delete all the others that single file will still have a high chance of failure) as long as node 12, sodium-native and tap coverage collection are involved.

2. Using `sodium-native` directly inside tests doesn't cause any issue for example

```js
const sodium = require('sodium-native')

test('foo', t => {
  const key = Buffer.allocUnsafe(sodium.crypto_secretbox_KEYBYTES)
  sodium.randombytes_buf(key)
  
  t.type(key, 'object')
})
```

This will work fine

3. Crashes only happen when you execute the tests using `npm run test` or `npx tap ./test/*.js`, running the test directly with node works fine (`node ./test/decorators.js` will run and pass)

4. in `decorators.js` test, if you go into the plugin (`index.js`) code and remove all object look ups on the sodium object and method calls from the sodium object, and entirely remove encryption/decryption/key generation, the test will pass and won't crash.

5. In `decorators.js` test, if you change the test to:

```js
'use strict'

// const fastify = require('fastify')({ logger: false })
const t = require('tap')
const sodium = require('sodium-native')
const key = Buffer.alloc(sodium.crypto_secretbox_KEYBYTES)
sodium.randombytes_buf(key)

// t.teardown(fastify.close.bind(fastify))

t.test('it exposes encode and decode decorators for other libraries to use', async () => {
  t.ok(1)

  let encoder = null
  let decoder = null
  let create = null

  require('..')({
    decorate (key, val) {
      if (key === 'encodeSecureSession') {
        encoder = val
      } else if (key === 'decodeSecureSession') {
        decoder = val
      } else if (key === 'createSecureSession') {
        create = val
      }

      return this
    },
    decorateRequest () {
      return this
    },
    register () {
      return this
    }
  }, { key }, (obj) => {
    if (obj instanceof Error) {
      throw obj
    }
  })

  const obj = create({ foo: 'bar' })
  const cookie = encoder(obj)
  const objDecoded = decoder(cookie)

  t.type(obj, 'object')
  t.type(cookie, 'string')
  t.type(objDecoded, 'object')
  t.same(obj, objDecoded)
})
```

`decorators.js` will always pass regardless of whether or not you run other tests with it.

4. All tests fail with the exact same error 

stuffing

**Comment by mcollina** [comment]
@mafintosh @emilbayes have you got any clue? It seems sodium-native is crashing in some really weird case.

**Comment by zekth** [comment]
Gentle bump: @mafintosh @emilbayes do you have any clue about this issue?

**Comment by mafintosh** [comment]
Which sodium-native version is this and do you know what API you're using?

**Comment by zekth** [comment]
`"sodium-native": "^3.0.0"`

@MSE99 explained everything in this comment: https://github.com/fastify/fastify-secure-session/pull/71#issuecomment-831190440
We're using this API:
```js
const sodium = require('sodium-native')
const key = Buffer.alloc(sodium.crypto_secretbox_KEYBYTES)
sodium.randombytes_buf(key)
```

**Comment by mafintosh** [comment]
Are you calling that from a worker or something? Do you have a sodium test case that fails or anything like that?

**Comment by zekth** [comment]
> Are you calling that from a worker or something? Do you have a sodium test case that fails or anything like that?

It's called using `node-tap`

**Comment by Fdawgs** [comment]
@is2ei's work has superseded this

**Pull request closed without merging**
